// Identificadores de Globex, sembrados por el seed. Acme no deberia poder ni verlos.
export const GLOBEX = {
  tenantId: '22222222-2222-4222-8222-222222222222',
  adminRoleId: 'b0000000-0000-4000-8000-000000000001',
  betoUserId: 'c0000000-0000-4000-8000-000000000002',
  unitId: 'e0000000-0000-4000-8000-000000000101',
  categoryId: 'e1000000-0000-4000-8000-000000000101',
  taxId: 'e2000000-0000-4000-8000-000000000101',
  warehouseId: 'e3000000-0000-4000-8000-000000000101',
  priceListId: 'e6000000-0000-4000-8000-000000000101',
  itemId: 'e4000000-0000-4000-8000-000000000101',
  confirmedAdjustmentId: 'e5000000-0000-4000-8000-000000000101',
  draftAdjustmentId: 'e5000000-0000-4000-8000-000000000102',
  supplierId: 'e8000000-0000-4000-8000-000000000101',
  confirmedOrderId: 'e9000000-0000-4000-8000-000000000101',
  confirmedOrderLineId: 'ea000000-0000-4000-8000-000000000101',
  draftOrderId: 'e9000000-0000-4000-8000-000000000102',
  draftReceiptId: 'eb000000-0000-4000-8000-000000000101',
  customerId: 'ed000000-0000-4000-8000-000000000101',
  partialSalesOrderId: 'ee000000-0000-4000-8000-000000000101',
  partialSalesOrderLineId: 'ef000000-0000-4000-8000-000000000101',
  draftSalesOrderId: 'ee000000-0000-4000-8000-000000000102',
  confirmedDispatchId: 'f1000000-0000-4000-8000-000000000101',
  draftDispatchId: 'f1000000-0000-4000-8000-000000000102',
  issuedInvoiceId: 'f3000000-0000-4000-8000-000000000101',
  confirmedPaymentId: 'd3000000-0000-4000-8000-000000000101',
  draftPaymentId: 'd3000000-0000-4000-8000-000000000102',
  exchangeRateId: 'f6000000-0000-4000-8000-000000000101',
};

export const ACME = {
  anaUserId: 'c0000000-0000-4000-8000-000000000001',
  viewerRoleId: 'a0000000-0000-4000-8000-000000000002',
  unitId: 'e0000000-0000-4000-8000-000000000001',
  supplierId: 'e8000000-0000-4000-8000-000000000001',
  mainWarehouseId: 'e3000000-0000-4000-8000-000000000001',
  waterItemId: 'e4000000-0000-4000-8000-000000000001',
};

export interface IsolationCase {
  // "METODO /ruta/con/:parametros" tal como la declara el controlador.
  route: string;
  title: string;
  method: 'get' | 'post' | 'put' | 'delete';
  path: string;
  body?: Record<string, unknown>;
}

// Cada endpoint que recibe un identificador, atacado con datos de Globex desde una
// sesion de Acme con TODOS los permisos. Si falla aqui, no es un permiso: es una fuga.
export const ISOLATION_CASES: IsolationCase[] = [
  {
    route: 'PUT /api/v1/company/exchange-rates/:rateId/status',
    title: 'deactivate an exchange rate of another tenant',
    method: 'put',
    path: `/api/v1/company/exchange-rates/${GLOBEX.exchangeRateId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/users/:userId',
    title: 'edit a person of another tenant',
    method: 'put',
    path: `/api/v1/users/${GLOBEX.betoUserId}`,
    body: { name: 'Colado', roleIds: [] },
  },
  {
    route: 'PUT /api/v1/users/:userId/status',
    title: 'deactivate a person of another tenant',
    method: 'put',
    path: `/api/v1/users/${GLOBEX.betoUserId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/roles/:roleId',
    title: 'rewrite a role of another tenant',
    method: 'put',
    path: `/api/v1/roles/${GLOBEX.adminRoleId}`,
    body: { name: 'Colado', permissions: [] },
  },
  {
    route: 'POST /api/v1/roles/assignments',
    title: 'grant a role of another tenant',
    method: 'post',
    path: '/api/v1/roles/assignments',
    body: { userId: ACME.anaUserId, roleId: GLOBEX.adminRoleId },
  },
  {
    route: 'DELETE /api/v1/roles/assignments',
    title: 'take a role away from a person of another tenant',
    method: 'delete',
    path: '/api/v1/roles/assignments',
    body: { userId: GLOBEX.betoUserId, roleId: GLOBEX.adminRoleId },
  },
  {
    route: 'POST /api/v1/users',
    title: 'create a person with a role of another tenant',
    method: 'post',
    path: '/api/v1/users',
    body: {
      email: 'colado-matriz@acme.com',
      password: 'a-long-password',
      name: 'Colado',
      roleIds: [GLOBEX.adminRoleId],
    },
  },
  {
    route: 'PUT /api/v1/catalog/categories/:categoryId',
    title: 'rename a category of another tenant',
    method: 'put',
    path: `/api/v1/catalog/categories/${GLOBEX.categoryId}`,
    body: { name: 'Colado' },
  },
  {
    route: 'PUT /api/v1/catalog/categories/:categoryId/status',
    title: 'deactivate a category of another tenant',
    method: 'put',
    path: `/api/v1/catalog/categories/${GLOBEX.categoryId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/catalog/units/:unitId',
    title: 'rename a measurement unit of another tenant',
    method: 'put',
    path: `/api/v1/catalog/units/${GLOBEX.unitId}`,
    body: { name: 'Colado', abbreviation: 'col' },
  },
  {
    route: 'PUT /api/v1/catalog/units/:unitId/status',
    title: 'deactivate a measurement unit of another tenant',
    method: 'put',
    path: `/api/v1/catalog/units/${GLOBEX.unitId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/catalog/taxes/:taxId',
    title: 'change the rate of a tax of another tenant',
    method: 'put',
    path: `/api/v1/catalog/taxes/${GLOBEX.taxId}`,
    body: { name: 'Colado', rate: 0 },
  },
  {
    route: 'PUT /api/v1/catalog/taxes/:taxId/status',
    title: 'deactivate a tax of another tenant',
    method: 'put',
    path: `/api/v1/catalog/taxes/${GLOBEX.taxId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/catalog/warehouses/:warehouseId',
    title: 'rename a warehouse of another tenant',
    method: 'put',
    path: `/api/v1/catalog/warehouses/${GLOBEX.warehouseId}`,
    body: { name: 'Colado' },
  },
  {
    route: 'PUT /api/v1/catalog/warehouses/:warehouseId/status',
    title: 'deactivate a warehouse of another tenant',
    method: 'put',
    path: `/api/v1/catalog/warehouses/${GLOBEX.warehouseId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/catalog/warehouses/:warehouseId/default',
    title: 'take the default mark with a warehouse of another tenant',
    method: 'put',
    path: `/api/v1/catalog/warehouses/${GLOBEX.warehouseId}/default`,
  },
  {
    route: 'PUT /api/v1/catalog/price-lists/:priceListId',
    title: 'rename a price list of another tenant',
    method: 'put',
    path: `/api/v1/catalog/price-lists/${GLOBEX.priceListId}`,
    body: { name: 'Colada' },
  },
  {
    route: 'PUT /api/v1/catalog/price-lists/:priceListId/status',
    title: 'deactivate a price list of another tenant',
    method: 'put',
    path: `/api/v1/catalog/price-lists/${GLOBEX.priceListId}/status`,
    body: { active: false },
  },
  {
    route: 'PUT /api/v1/catalog/price-lists/:priceListId/default',
    title: 'take the default mark with a price list of another tenant',
    method: 'put',
    path: `/api/v1/catalog/price-lists/${GLOBEX.priceListId}/default`,
  },
  {
    route: 'PUT /api/v1/inventory/items/:itemId',
    title: 'rewrite an item of another tenant',
    method: 'put',
    path: `/api/v1/inventory/items/${GLOBEX.itemId}`,
    body: {
      sku: 'COLADO',
      name: 'Colado',
      type: 'service',
      units: [{ unitId: GLOBEX.unitId, conversionFactor: 1, isBase: true }],
    },
  },
  {
    route: 'PUT /api/v1/inventory/items/:itemId/status',
    title: 'deactivate an item of another tenant',
    method: 'put',
    path: `/api/v1/inventory/items/${GLOBEX.itemId}/status`,
    body: { active: false },
  },
  {
    // Cada referencia por separado seria mas exhaustivo; con la unidad basta para ver
    // que el articulo no puede apuntar fuera de su empresa. La categoria y el impuesto
    // ajenos los cubren las pruebas de aplicacion.
    route: 'POST /api/v1/inventory/items',
    title: 'create an item that uses a unit of another tenant',
    method: 'post',
    path: '/api/v1/inventory/items',
    body: {
      sku: `COLADO-${Date.now()}`,
      name: 'Colado',
      type: 'inventoried',
      units: [{ unitId: GLOBEX.unitId, conversionFactor: 1, isBase: true }],
    },
  },
  {
    route: 'PUT /api/v1/inventory/adjustments/:adjustmentId',
    title: 'rewrite a draft adjustment of another tenant',
    method: 'put',
    path: `/api/v1/inventory/adjustments/${GLOBEX.draftAdjustmentId}`,
    body: { warehouseId: GLOBEX.warehouseId, lines: [{ itemId: GLOBEX.itemId, unitId: GLOBEX.unitId, direction: 'in', quantity: 999 }] },
  },
  {
    route: 'PUT /api/v1/inventory/adjustments/:adjustmentId/confirm',
    title: 'confirm a draft adjustment of another tenant and move its stock',
    method: 'put',
    path: `/api/v1/inventory/adjustments/${GLOBEX.draftAdjustmentId}/confirm`,
  },
  {
    route: 'PUT /api/v1/inventory/adjustments/:adjustmentId/cancel',
    title: 'cancel a confirmed adjustment of another tenant and reverse its stock',
    method: 'put',
    path: `/api/v1/inventory/adjustments/${GLOBEX.confirmedAdjustmentId}/cancel`,
  },
  {
    route: 'POST /api/v1/inventory/adjustments',
    title: 'create an adjustment in a warehouse of another tenant',
    method: 'post',
    path: '/api/v1/inventory/adjustments',
    body: { warehouseId: GLOBEX.warehouseId, lines: [{ itemId: GLOBEX.itemId, unitId: GLOBEX.unitId, direction: 'out', quantity: 1 }] },
  },
  {
    route: 'GET /api/v1/inventory/items/:itemId/movements',
    title: 'read the kardex of an item of another tenant',
    method: 'get',
    path: `/api/v1/inventory/items/${GLOBEX.itemId}/movements`,
  },
  {
    route: 'GET /api/v1/inventory/stock',
    title: 'filter the stock by a warehouse of another tenant',
    method: 'get',
    path: `/api/v1/inventory/stock?warehouseId=${GLOBEX.warehouseId}`,
  },
  {
    route: 'GET /api/v1/inventory/low-stock',
    title: 'ask what is below the minimum in a warehouse of another tenant',
    method: 'get',
    path: `/api/v1/inventory/low-stock?warehouseId=${GLOBEX.warehouseId}`,
  },
  {
    route: 'PUT /api/v1/purchasing/suppliers/:supplierId',
    title: 'rename a supplier of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/suppliers/${GLOBEX.supplierId}`,
    body: { name: 'Colado' },
  },
  {
    route: 'PUT /api/v1/purchasing/suppliers/:supplierId/status',
    title: 'deactivate a supplier of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/suppliers/${GLOBEX.supplierId}/status`,
    body: { active: false },
  },
  {
    route: 'POST /api/v1/purchasing/orders',
    title: 'order from a supplier of another tenant',
    method: 'post',
    path: '/api/v1/purchasing/orders',
    body: {
      supplierId: GLOBEX.supplierId,
      warehouseId: ACME.mainWarehouseId,
      lines: [{ itemId: ACME.waterItemId, unitId: ACME.unitId, quantity: 1, unitCost: 1 }],
    },
  },
  {
    route: 'PUT /api/v1/purchasing/orders/:orderId',
    title: 'rewrite a draft purchase order of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/orders/${GLOBEX.draftOrderId}`,
    body: {
      supplierId: GLOBEX.supplierId,
      warehouseId: GLOBEX.warehouseId,
      lines: [{ itemId: GLOBEX.itemId, unitId: GLOBEX.unitId, quantity: 999, unitCost: 1 }],
    },
  },
  {
    route: 'PUT /api/v1/purchasing/orders/:orderId/confirm',
    title: 'confirm a draft purchase order of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/orders/${GLOBEX.draftOrderId}/confirm`,
  },
  {
    route: 'PUT /api/v1/purchasing/orders/:orderId/cancel',
    title: 'cancel a confirmed purchase order of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/orders/${GLOBEX.confirmedOrderId}/cancel`,
  },
  {
    route: 'POST /api/v1/purchasing/receipts',
    title: 'receive goods for an order of another tenant',
    method: 'post',
    path: '/api/v1/purchasing/receipts',
    body: { orderId: GLOBEX.confirmedOrderId, lines: [{ orderLineId: GLOBEX.confirmedOrderLineId, quantity: 1 }] },
  },
  {
    route: 'PUT /api/v1/purchasing/receipts/:receiptId',
    title: 'rewrite a draft goods receipt of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/receipts/${GLOBEX.draftReceiptId}`,
    body: { lines: [{ orderLineId: GLOBEX.confirmedOrderLineId, quantity: 1 }] },
  },
  {
    route: 'PUT /api/v1/purchasing/receipts/:receiptId/confirm',
    title: 'confirm a goods receipt of another tenant and move its stock',
    method: 'put',
    path: `/api/v1/purchasing/receipts/${GLOBEX.draftReceiptId}/confirm`,
  },
  {
    route: 'PUT /api/v1/purchasing/receipts/:receiptId/cancel',
    title: 'cancel a goods receipt of another tenant',
    method: 'put',
    path: `/api/v1/purchasing/receipts/${GLOBEX.draftReceiptId}/cancel`,
  },
  {
    route: 'GET /api/v1/purchasing/incoming',
    title: 'filter the goods in transit by a warehouse of another tenant',
    method: 'get',
    path: `/api/v1/purchasing/incoming?warehouseId=${GLOBEX.warehouseId}`,
  },
  {
    route: 'PUT /api/v1/sales/customers/:customerId',
    title: 'rename a customer of another tenant',
    method: 'put',
    path: `/api/v1/sales/customers/${GLOBEX.customerId}`,
    body: { name: 'Colado' },
  },
  {
    route: 'PUT /api/v1/sales/customers/:customerId/status',
    title: 'deactivate a customer of another tenant',
    method: 'put',
    path: `/api/v1/sales/customers/${GLOBEX.customerId}/status`,
    body: { active: false },
  },
  {
    route: 'POST /api/v1/sales/orders',
    title: 'sell to a customer of another tenant',
    method: 'post',
    path: '/api/v1/sales/orders',
    body: { customerId: GLOBEX.customerId, warehouseId: ACME.mainWarehouseId, lines: [{ itemId: ACME.waterItemId, unitId: ACME.unitId, quantity: 1, unitPrice: 1 }] },
  },
  {
    route: 'PUT /api/v1/sales/orders/:orderId',
    title: 'rewrite a draft sales order of another tenant',
    method: 'put',
    path: `/api/v1/sales/orders/${GLOBEX.draftSalesOrderId}`,
    body: { customerId: GLOBEX.customerId, warehouseId: GLOBEX.warehouseId, lines: [{ itemId: GLOBEX.itemId, unitId: GLOBEX.unitId, quantity: 999, unitPrice: 1 }] },
  },
  {
    route: 'PUT /api/v1/sales/orders/:orderId/confirm',
    title: 'confirm a sales order of another tenant and reserve its stock',
    method: 'put',
    path: `/api/v1/sales/orders/${GLOBEX.draftSalesOrderId}/confirm`,
  },
  {
    route: 'PUT /api/v1/sales/orders/:orderId/cancel',
    title: 'cancel a sales order of another tenant',
    method: 'put',
    path: `/api/v1/sales/orders/${GLOBEX.partialSalesOrderId}/cancel`,
  },
  {
    route: 'POST /api/v1/sales/dispatches',
    title: 'dispatch goods of an order of another tenant',
    method: 'post',
    path: '/api/v1/sales/dispatches',
    body: { orderId: GLOBEX.partialSalesOrderId, lines: [{ orderLineId: GLOBEX.partialSalesOrderLineId, quantity: 1 }] },
  },
  {
    route: 'PUT /api/v1/sales/dispatches/:dispatchId',
    title: 'rewrite a draft dispatch of another tenant',
    method: 'put',
    path: `/api/v1/sales/dispatches/${GLOBEX.draftDispatchId}`,
    body: { lines: [{ orderLineId: GLOBEX.partialSalesOrderLineId, quantity: 1 }] },
  },
  {
    route: 'PUT /api/v1/sales/dispatches/:dispatchId/confirm',
    title: 'confirm a dispatch of another tenant and take its stock',
    method: 'put',
    path: `/api/v1/sales/dispatches/${GLOBEX.draftDispatchId}/confirm`,
  },
  {
    route: 'PUT /api/v1/sales/dispatches/:dispatchId/cancel',
    title: 'cancel a dispatch of another tenant',
    method: 'put',
    path: `/api/v1/sales/dispatches/${GLOBEX.draftDispatchId}/cancel`,
  },
  {
    route: 'POST /api/v1/sales/invoices',
    title: 'invoice a dispatch of another tenant',
    method: 'post',
    path: '/api/v1/sales/invoices',
    body: { dispatchId: GLOBEX.confirmedDispatchId },
  },
  {
    route: 'PUT /api/v1/sales/invoices/:invoiceId/cancel',
    title: 'cancel an invoice of another tenant',
    method: 'put',
    path: `/api/v1/sales/invoices/${GLOBEX.issuedInvoiceId}/cancel`,
  },
  {
    route: 'GET /api/v1/sales/availability',
    title: 'filter the availability by a warehouse of another tenant',
    method: 'get',
    path: `/api/v1/sales/availability?warehouseId=${GLOBEX.warehouseId}`,
  },
  {
    route: 'POST /api/v1/receivables/payments',
    title: 'register a payment for a customer and an invoice of another tenant',
    method: 'post',
    path: '/api/v1/receivables/payments',
    body: { customerId: GLOBEX.customerId, method: 'cash', allocations: [{ invoiceId: GLOBEX.issuedInvoiceId, amount: 1 }] },
  },
  {
    route: 'PUT /api/v1/receivables/payments/:paymentId',
    title: 'rewrite a draft payment of another tenant',
    method: 'put',
    path: `/api/v1/receivables/payments/${GLOBEX.draftPaymentId}`,
    body: { customerId: GLOBEX.customerId, method: 'cash', allocations: [{ invoiceId: GLOBEX.issuedInvoiceId, amount: 50 }] },
  },
  {
    route: 'PUT /api/v1/receivables/payments/:paymentId/confirm',
    title: 'confirm a payment of another tenant and lower its balances',
    method: 'put',
    path: `/api/v1/receivables/payments/${GLOBEX.draftPaymentId}/confirm`,
  },
  {
    route: 'PUT /api/v1/receivables/payments/:paymentId/cancel',
    title: 'cancel a payment of another tenant and raise its balances',
    method: 'put',
    path: `/api/v1/receivables/payments/${GLOBEX.confirmedPaymentId}/cancel`,
  },
  {
    route: 'GET /api/v1/receivables/invoices',
    title: 'list the receivables of a customer of another tenant',
    method: 'get',
    path: `/api/v1/receivables/invoices?customerId=${GLOBEX.customerId}`,
  },
  {
    route: 'GET /api/v1/receivables/customers/:customerId/statement',
    title: 'read the statement of a customer of another tenant',
    method: 'get',
    path: `/api/v1/receivables/customers/${GLOBEX.customerId}/statement`,
  },
  {
    route: 'GET /api/v1/reports/customers/:customerId/statement',
    title: 'read the printable statement of a customer of another tenant',
    method: 'get',
    path: `/api/v1/reports/customers/${GLOBEX.customerId}/statement`,
  },
  {
    route: 'GET /api/v1/reports/customers/:customerId/statement/export',
    title: 'download the statement of a customer of another tenant',
    method: 'get',
    path: `/api/v1/reports/customers/${GLOBEX.customerId}/statement/export?format=pdf`,
  },
  {
    route: 'GET /api/v1/reports/inventory-valuation',
    title: 'value the stock of a warehouse of another tenant',
    method: 'get',
    path: `/api/v1/reports/inventory-valuation?warehouseId=${GLOBEX.warehouseId}`,
  },
  {
    route: 'GET /api/v1/reports/inventory-valuation/export',
    title: 'download the stock valuation of a warehouse of another tenant',
    method: 'get',
    path: `/api/v1/reports/inventory-valuation/export?format=xlsx&warehouseId=${GLOBEX.warehouseId}`,
  },
];
